rep68-easier:
   out_directory: "../../out/experiment1_OTC-AAV-rep68_chr1"
   
   # integration simulation
   replicates: 3 
   hosts: 
      chr1 : "../../data/references/chrs/chr1.fa"
       
   viruses:
      rep68 :  "../../data/references/test_AAV.fa"
   
   initial_seed: 12345
   seed_increment: 123 
   int_num: 
       - 1000
   epi_num:
       - 0
   p_whole:
       - 1
   p_rearrange:
       - 0
   p_delete:
       - 0
   lambda_split:
       - 1
   p_overlap:
       - 0
   p_gap:
       - 0
   lambda_junction:
       - 5
   p_host_deletion:
       - 0
   lambda_host_deletion:
       - 500
   min_sep:
       - 500
   # read simulation
   read_len: 
       - 150
   fcov: 
       - 5 
   frag_len: 
       - 500 
   frag_std: 
       - 30
   seq_sys: 
       - "HS25"

   # analysis
   analysis_hosts: 
      chr1 : "../../data/references/chrs/chr1.fa"
      hg38: "../../data/references/GRCh38.fa"
       
   analysis_viruses:
      rep68 :  "../../data/references/test_AAV.fa"
   merge: 
       - True
   dedup: 
       - False
   post:
       -
         - filter
         - mask-exclude:
           - "../../data/references/hg38_homologoustoOTCvec.bed"
   bwa_mem:
       - "-A 1 -B 2 -O 6,6 -E 1,1 -L 0,0 -T 10 -h 200"
   
   polyidus_params:
     aligner:
      - "bowtie2"
      
   # scoring
   score_ints: True
   score_ints_window: 20 # window either side of simulated integrations to look for detected integrations

  

OTC-vect-easier:
   out_directory: "../../out/experiment1_OTC-AAV-rep68_chr1"
   
   # integration simulation
   replicates: 3 
   hosts: 
      chr1 : "../../data/references/chrs/chr1.fa"
       
   viruses:
      OTC :  "../../data/references/OTC-vec_rAAV-genome-only.fa"
   
   initial_seed: 12345
   seed_increment: 123 
   int_num: 
       - 1000
   epi_num:
       - 0
   p_whole:
       - 1
   p_rearrange:
       - 0
   p_delete:
       - 0
   lambda_split:
       - 1
   p_overlap:
       - 0
   p_gap:
       - 0
   lambda_junction:
       - 5
   p_host_deletion:
       - 0
   lambda_host_deletion:
       - 500
   min_sep:
       - 500
   # read simulation
   read_len: 
       - 150
   fcov: 
       - 5 
   frag_len: 
       - 500 
   frag_std: 
       - 30
   seq_sys: 
       - "HS25"

   # analysis
   analysis_hosts: 
      chr1 : "../../data/references/chrs/chr1.fa"
      hg38: "../../data/references/GRCh38.fa"
       
   analysis_viruses:
      OTC :  "../../data/references/OTC-vec_rAAV-genome-only.fa"
   merge: 
       - True
   dedup: 
       - False
   post:
       -
         - filter
         - mask-exclude:
           - "../../data/references/hg38_homologoustoOTCvec.bed"
   bwa_mem:
       - "-A 1 -B 2 -O 6,6 -E 1,1 -L 0,0 -T 10 -h 200"
       
       
   polyidus_params:
     aligner:
      - "bowtie2"
      
   # scoring
   score_ints: True
   score_ints_window: 20 # window either side of simulated integrations to look for detected integrations

  
  
AAV2-easier:
   out_directory: "../../out/experiment1_OTC-AAV-rep68_chr1"
   
   # integration simulation
   replicates: 3 
   hosts: 
      chr1 : "../../data/references/chrs/chr1.fa"
       
   viruses:
      AAV2 :  "../../data/references/NC_001401.2.fa"
   
   initial_seed: 12345
   seed_increment: 123 
   int_num: 
       - 1000
   epi_num:
       - 0
   p_whole:
       - 1
   p_rearrange:
       - 0
   p_delete:
       - 0
   lambda_split:
       - 1
   p_overlap:
       - 0
   p_gap:
       - 0
   lambda_junction:
       - 5
   p_host_deletion:
       - 0
   lambda_host_deletion:
       - 500
   min_sep:
       - 500
   # read simulation
   read_len: 
       - 150
   fcov: 
       - 5 
   frag_len: 
       - 500 
   frag_std: 
       - 30
   seq_sys: 
       - "HS25"

   # analysis
   analysis_hosts: 
      chr1 : "../../data/references/chrs/chr1.fa"
      hg38: "../../data/references/GRCh38.fa"
       
   analysis_viruses:
      AAV2 :  "../../data/references/NC_001401.2.fa"
   merge: 
       - True
   dedup: 
       - False
   post:
       -
         - filter
         - mask-exclude:
           - "../../data/references/hg38_homologoustoOTCvec.bed"
   bwa_mem:
       - "-A 1 -B 2 -O 6,6 -E 1,1 -L 0,0 -T 10 -h 200" 
       
       
   polyidus_params:
     aligner:
      - "bowtie2"
      
   # scoring
   score_ints: True
   score_ints_window: 20 # window either side of simulated integrations to look for detected integrations

       
OTC-vect-harder:
   out_directory: "../../out/experiment1_OTC-AAV-rep68_chr1"
   
   # integration simulation
   replicates: 3 
   hosts: 
      chr1 : "../../data/references/chrs/chr1.fa"
       
   viruses:
      OTC :  "../../data/references/OTC-vec_rAAV-genome-only.fa"
   
   initial_seed: 12345
   seed_increment: 123 
   int_num: 
       - 1000
   epi_num:
       - 1000
   p_whole:
       - 0.3
   p_rearrange:
       - 0.1
   p_delete:
       - 0.1
   lambda_split:
       - 1
   p_overlap:
       - 0.3
   p_gap:
       - 0.3
   lambda_junction:
       - 1
   p_host_deletion:
       - 0.5
   lambda_host_deletion:
       - 500
   min_sep:
       - 500
   # read simulation
   read_len: 
       - 150
   fcov: 
       - 5 
   frag_len: 
       - 500 
   frag_std: 
       - 30
   seq_sys: 
       - "HS25"

   # analysis
   analysis_hosts: 
      chr1 : "../../data/references/chrs/chr1.fa"
      hg38: "../../data/references/GRCh38.fa"
       
   analysis_viruses:
      OTC :  "../../data/references/OTC-vec_rAAV-genome-only.fa"
   merge: 
       - True
   dedup: 
       - False
   post:
       -
         - filter
         - mask-exclude:
           - "../../data/references/hg38_homologoustoOTCvec.bed"
   bwa_mem:
       - "-A 1 -B 2 -O 6,6 -E 1,1 -L 0,0 -T 10 -h 200"
       
       
   polyidus_params:
     aligner:
      - "bowtie2"
      
      
   # scoring
   score_ints: True
   score_ints_window: 20 # window either side of simulated integrations to look for detected integrations



AAV2-harder:
   out_directory: "../../out/experiment1_OTC-AAV-rep68_chr1"
   
   # integration simulation
   replicates: 3 
   hosts: 
      chr1 : "../../data/references/chrs/chr1.fa"
       
   viruses:
      AAV2 :  "../../data/references/NC_001401.2.fa"
   
   initial_seed: 12345
   seed_increment: 123 
   int_num: 
       - 1000
   epi_num:
       - 1000
   p_whole:
       - 0.3
   p_rearrange:
       - 0.1
   p_delete:
       - 0.1
   lambda_split:
       - 1
   p_overlap:
       - 0.3
   p_gap:
       - 0.3
   lambda_junction:
       - 1
   p_host_deletion:
       - 0.5
   lambda_host_deletion:
       - 500
   min_sep:
       - 500
   # read simulation
   read_len: 
       - 150
   fcov: 
       - 5 
   frag_len: 
       - 500 
   frag_std: 
       - 30
   seq_sys: 
       - "HS25"
   # analysis
   analysis_hosts: 
      chr1 : "../../data/references/chrs/chr1.fa"
      hg38: "../../data/references/GRCh38.fa"
       
   analysis_viruses:
      AAV2 :  "../../data/references/NC_001401.2.fa"
   merge: 
       - True
   dedup: 
       - False
   post:
       -
         - filter
         - mask-exclude:
           - "../../data/references/hg38_homologoustoOTCvec.bed"
   bwa_mem:
       - "-A 1 -B 2 -O 6,6 -E 1,1 -L 0,0 -T 10 -h 200" 
       
       
   polyidus_params:
     aligner:
      - "bowtie2"
      
      
   # scoring
   score_ints: True
   score_ints_window: 20 # window either side of simulated integrations to look for detected integrations

       

rep68-harder:
   out_directory: "../../out/experiment1_OTC-AAV-rep68_chr1"
   
   # integration simulation
   replicates: 3 
   hosts: 
      chr1 : "../../data/references/chrs/chr1.fa"
       
   viruses:
      rep68 :  "../../data/references/test_AAV.fa"
   
   initial_seed: 12345
   seed_increment: 123 
   int_num: 
       - 1000
   epi_num:
       - 1000
   p_whole:
       - 0.3
   p_rearrange:
       - 0.1
   p_delete:
       - 0.1
   lambda_split:
       - 1
   p_overlap:
       - 0.3
   p_gap:
       - 0.3
   lambda_junction:
       - 1
   p_host_deletion:
       - 0.5
   lambda_host_deletion:
       - 500
   min_sep:
       - 500
   # read simulation
   read_len: 
       - 150
   fcov: 
       - 5 
   frag_len: 
       - 500 
   frag_std: 
       - 30
   seq_sys: 
       - "HS25"
   # analysis
   analysis_hosts: 
      chr1 : "../../data/references/chrs/chr1.fa"
      hg38: "../../data/references/GRCh38.fa"
       
   analysis_viruses:
      rep68 :  "../../data/references/test_AAV.fa"
   merge: 
       - True
   dedup: 
       - False
   post:
       -
         - filter
         - mask-exclude:
           - "../../data/references/hg38_homologoustoOTCvec.bed"
   bwa_mem:
       - "-A 1 -B 2 -O 6,6 -E 1,1 -L 0,0 -T 10 -h 200" 
       
   polyidus_params:
     aligner:
      - "bowtie2"
      
      
   # scoring
   score_ints: True
   score_ints_window: 20 # window either side of simulated integrations to look for detected integrations

