rep68-easier:
   out_directory: "../../out/experiment0_prelim"
   
   # integration simulation
   replicates: 3 
   hosts: 
      chr1 : "../../data/references/chrs/chr1.fa"
       
   viruses:
      rep68 :  "../../data/references/test_AAV.fa"
   
   initial_seed: 12345
   seed_increment: 123 
   int_num: 
       - 1000
   epi_num:
       - 0
   p_whole:
       - 1
   p_rearrange:
       - 0
   p_delete:
       - 0
   lambda_split:
       - 1
   p_overlap:
       - 0
   p_gap:
       - 0
   lambda_junction:
       - 5
   p_host_deletion:
       - 0
   lambda_host_deletion:
       - 500
   # read simulation
   read_len: 
       - 150
   fcov: 
       - 5 
   frag_len: 
       - 500 
   frag_std: 
       - 30
   seq_sys: 
       - "HS25"

   # analysis
   analysis_hosts: 
      chr1 : "../../data/references/chrs/chr1.fa"
      hg38: "../../data/references/GRCh38.fa"
       
   analysis_viruses:
      rep68 :  "../../data/references/test_AAV.fa"
   merge: 
       - True
   dedup: 
       - False
   post:
       -
         - filter
   bwa_mem:
       - "-A 1 -B 2 -O 6,6 -E 1,1 -L 0,0 -T 10 -h 200"


rep68-whole:
   out_directory: "../../out/experiment0_prelim"
   
   # integration simulation
   replicates: 3 
   hosts: 
      chr1 : "../../data/references/chrs/chr1.fa"
       
   viruses:
      rep68 :  "../../data/references/test_AAV.fa"
   
   initial_seed: 12345
   seed_increment: 123 
   int_num: 
       - 1000
   epi_num:
       - 0
   p_whole:
       - 0.3
   p_rearrange:
       - 0
   p_delete:
       - 0
   lambda_split:
       - 1
   p_overlap:
       - 0
   p_gap:
       - 0
   lambda_junction:
       - 5
   p_host_deletion:
       - 0
   lambda_host_deletion:
       - 500
   # read simulation
   read_len: 
       - 150
   fcov: 
       - 5 
   frag_len: 
       - 500 
   frag_std: 
       - 30
   seq_sys: 
       - "HS25"

   # analysis
   analysis_hosts: 
      chr1 : "../../data/references/chrs/chr1.fa"
      hg38: "../../data/references/GRCh38.fa"
       
   analysis_viruses:
      rep68 :  "../../data/references/test_AAV.fa"
   merge: 
       - True
   dedup: 
       - False
   post:
       -
         - filter
   bwa_mem:
       - "-A 1 -B 2 -O 6,6 -E 1,1 -L 0,0 -T 10 -h 200"
 
rep68-epi:
   out_directory: "../../out/experiment0_prelim"
   
   # integration simulation
   replicates: 3 
   hosts: 
      chr1 : "../../data/references/chrs/chr1.fa"
       
   viruses:
      rep68 :  "../../data/references/test_AAV.fa"
   
   initial_seed: 12345
   seed_increment: 123 
   int_num: 
       - 1000
   epi_num:
       - 1000
   p_whole:
       - 1
   p_rearrange:
       - 0
   p_delete:
       - 0
   lambda_split:
       - 1
   p_overlap:
       - 0
   p_gap:
       - 0
   lambda_junction:
       - 5
   p_host_deletion:
       - 0
   lambda_host_deletion:
       - 500
   # read simulation
   read_len: 
       - 150
   fcov: 
       - 5 
   frag_len: 
       - 500 
   frag_std: 
       - 30
   seq_sys: 
       - "HS25"

   # analysis
   analysis_hosts: 
      chr1 : "../../data/references/chrs/chr1.fa"
      hg38: "../../data/references/GRCh38.fa"
       
   analysis_viruses:
      rep68 :  "../../data/references/test_AAV.fa"
   merge: 
       - True
   dedup: 
       - False
   post:
       -
         - filter
   bwa_mem:
       - "-A 1 -B 2 -O 6,6 -E 1,1 -L 0,0 -T 10 -h 200"
       
 
rep68-rearrange:
   out_directory: "../../out/experiment0_prelim"
   
   # integration simulation
   replicates: 3 
   hosts: 
      chr1 : "../../data/references/chrs/chr1.fa"
       
   viruses:
      rep68 :  "../../data/references/test_AAV.fa"
   
   initial_seed: 12345
   seed_increment: 123 
   int_num: 
       - 1000
   epi_num:
       - 0
   p_whole:
       - 1
   p_rearrange:
       - 0.1
   p_delete:
       - 0
   lambda_split:
       - 1
   p_overlap:
       - 0
   p_gap:
       - 0
   lambda_junction:
       - 5
   p_host_deletion:
       - 0
   lambda_host_deletion:
       - 500
   # read simulation
   read_len: 
       - 150
   fcov: 
       - 5 
   frag_len: 
       - 500 
   frag_std: 
       - 30
   seq_sys: 
       - "HS25"

   # analysis
   analysis_hosts: 
      chr1 : "../../data/references/chrs/chr1.fa"
      hg38: "../../data/references/GRCh38.fa"
       
   analysis_viruses:
      rep68 :  "../../data/references/test_AAV.fa"
   merge: 
       - True
   dedup: 
       - False
   post:
       -
         - filter
   bwa_mem:
       - "-A 1 -B 2 -O 6,6 -E 1,1 -L 0,0 -T 10 -h 200"
       
rep68-deletion:
   out_directory: "../../out/experiment0_prelim"
   
   # integration simulation
   replicates: 3 
   hosts: 
      chr1 : "../../data/references/chrs/chr1.fa"
       
   viruses:
      rep68 :  "../../data/references/test_AAV.fa"
   
   initial_seed: 12345
   seed_increment: 123 
   int_num: 
       - 1000
   epi_num:
       - 0
   p_whole:
       - 1
   p_rearrange:
       - 0
   p_delete:
       - 0.1
   lambda_split:
       - 1
   p_overlap:
       - 0
   p_gap:
       - 0
   lambda_junction:
       - 5
   p_host_deletion:
       - 0
   lambda_host_deletion:
       - 500
   # read simulation
   read_len: 
       - 150
   fcov: 
       - 5 
   frag_len: 
       - 500 
   frag_std: 
       - 30
   seq_sys: 
       - "HS25"

   # analysis
   analysis_hosts: 
      chr1 : "../../data/references/chrs/chr1.fa"
      hg38: "../../data/references/GRCh38.fa"
       
   analysis_viruses:
      rep68 :  "../../data/references/test_AAV.fa"
   merge: 
       - True
   dedup: 
       - False
   post:
       -
         - filter
   bwa_mem:
       - "-A 1 -B 2 -O 6,6 -E 1,1 -L 0,0 -T 10 -h 200"
       
rep68-overlap:
   out_directory: "../../out/experiment0_prelim"
   
   # integration simulation
   replicates: 3 
   hosts: 
      chr1 : "../../data/references/chrs/chr1.fa"
       
   viruses:
      rep68 :  "../../data/references/test_AAV.fa"
   
   initial_seed: 12345
   seed_increment: 123 
   int_num: 
       - 1000
   epi_num:
       - 0
   p_whole:
       - 1
   p_rearrange:
       - 0
   p_delete:
       - 0
   lambda_split:
       - 1
   p_overlap:
       - 0.3
   p_gap:
       - 0
   lambda_junction:
       - 5
   p_host_deletion:
       - 0
   lambda_host_deletion:
       - 500
   # read simulation
   read_len: 
       - 150
   fcov: 
       - 5 
   frag_len: 
       - 500 
   frag_std: 
       - 30
   seq_sys: 
       - "HS25"

   # analysis
   analysis_hosts: 
      chr1 : "../../data/references/chrs/chr1.fa"
      hg38: "../../data/references/GRCh38.fa"
       
   analysis_viruses:
      rep68 :  "../../data/references/test_AAV.fa"
   merge: 
       - True
   dedup: 
       - False
   post:
       -
         - filter
   bwa_mem:
       - "-A 1 -B 2 -O 6,6 -E 1,1 -L 0,0 -T 10 -h 200"
       
rep68-gap:
   out_directory: "../../out/experiment0_prelim"
   
   # integration simulation
   replicates: 3 
   hosts: 
      chr1 : "../../data/references/chrs/chr1.fa"
       
   viruses:
      rep68 :  "../../data/references/test_AAV.fa"
   
   initial_seed: 12345
   seed_increment: 123 
   int_num: 
       - 1000
   epi_num:
       - 0
   p_whole:
       - 1
   p_rearrange:
       - 0
   p_delete:
       - 0
   lambda_split:
       - 1
   p_overlap:
       - 0
   p_gap:
       - 0.3
   lambda_junction:
       - 5
   p_host_deletion:
       - 0
   lambda_host_deletion:
       - 500
   # read simulation
   read_len: 
       - 150
   fcov: 
       - 5 
   frag_len: 
       - 500 
   frag_std: 
       - 30
   seq_sys: 
       - "HS25"

   # analysis
   analysis_hosts: 
      chr1 : "../../data/references/chrs/chr1.fa"
      hg38: "../../data/references/GRCh38.fa"
       
   analysis_viruses:
      rep68 :  "../../data/references/test_AAV.fa"
   merge: 
       - True
   dedup: 
       - False
   post:
       -
         - filter
   bwa_mem:
       - "-A 1 -B 2 -O 6,6 -E 1,1 -L 0,0 -T 10 -h 200"
       
rep68-host_deletion:
   out_directory: "../../out/experiment0_prelim"
   
   # integration simulation
   replicates: 3 
   hosts: 
      chr1 : "../../data/references/chrs/chr1.fa"
       
   viruses:
      rep68 :  "../../data/references/test_AAV.fa"
   
   initial_seed: 12345
   seed_increment: 123 
   int_num: 
       - 1000
   epi_num:
       - 0
   p_whole:
       - 1
   p_rearrange:
       - 0
   p_delete:
       - 0
   lambda_split:
       - 1
   p_overlap:
       - 0
   p_gap:
       - 0
   lambda_junction:
       - 5
   p_host_deletion:
       - 0.5
   lambda_host_deletion:
       - 500
   # read simulation
   read_len: 
       - 150
   fcov: 
       - 5 
   frag_len: 
       - 500 
   frag_std: 
       - 30
   seq_sys: 
       - "HS25"

   # analysis
   analysis_hosts: 
      chr1 : "../../data/references/chrs/chr1.fa"
      hg38: "../../data/references/GRCh38.fa"
       
   analysis_viruses:
      rep68 :  "../../data/references/test_AAV.fa"
   merge: 
       - True
   dedup: 
       - False
   post:
       -
         - filter
   bwa_mem:
       - "-A 1 -B 2 -O 6,6 -E 1,1 -L 0,0 -T 10 -h 200"
