experiment1:
  read_folder: "../out/sim/experiment1/sim_reads/"
  host_name: "longer_host"
  host_fasta: "../data/references/longer_host.fa"
  virus_name: "test_virus"
  virus_fasta: "../data/references/test_virus.fa"
  merge: True
  dedup: True
  read1-adapt: "AGATCGGAAGAGCACACGTCTGAACTCCAGTCA"
  read2-adapt: "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"
  bam_suffix: ".sam"
  out_dir: "../out/sim/experiment1/pipeline/"
  post:
    - dedup
