frag_dist:
   out_directory: "../../out/experiment2_frag-len"
   
   # integration simulation
   replicates: 3 
   hosts: 
      chr1 : "../../data/references/chrs/chr1.fa"
       
   viruses:
      AAV2 :  "../../data/references/NC_001401.2.fa"
   
   initial_seed: 12345
   seed_increment: 123 
   int_num: 
       - 10
   epi_num:
       - 0
   p_whole:
       - .7
   p_rearrange:
       - 0.1
   p_delete:
       - 0.1
   lambda_split:
       - 1
   p_overlap:
       - 0.2
   p_gap:
       - 0.2
   lambda_junction:
       - 5
   p_host_deletion:
       - 0
   lambda_host_deletion:
       - 500
   # read simulation
   read_len: 
       - 150
   fcov: 
       - 5       
   frag_len: 
       - 150
       - 250
       - 300 
       - 600
       - 1000 
   frag_std: 
       - 30
       - 100
   seq_sys: 
       - "HS25"


   # analysis
   merge: 
       - True
   dedup: 
       - False
   post:
       -
         - dedup
   bwa_mem:
       - "-A 1 -B 2 -O 6,6 -E 1,1 -L 0,0 -T 10 -h 200"
   
   
OTC-harder-frag_len:
   out_directory: "../../out/experiment1_OTC-AAV-rep68_chr1"
   
   # integration simulation
   replicates: 3 
   hosts: 
      chr1 : "../../data/references/chrs/chr1.fa"
       
   viruses:
      OTC :  "../../data/references/OTC-vec_rAAV-genome-only.fa"
   
   initial_seed: 12345
   seed_increment: 123 
   int_num: 
       - 1000
   epi_num:
       - 1000
   p_whole:
       - 0.3
   p_rearrange:
       - 0.1
   p_delete:
       - 0.1
   lambda_split:
       - 1
   p_overlap:
       - 0.3
   p_gap:
       - 0.3
   lambda_junction:
       - 1
   p_host_deletion:
       - 0.5
   lambda_host_deletion:
       - 500
   min_sep:
       - 500
   # read simulation
   read_len: 
       - 150
   fcov: 
       - 5 
   frag_len: 
       - 150
       - 250
       - 300 
       - 600
       - 1000 
   frag_std: 
       - 30
       - 100
   seq_sys: 
       - "HS25"
   # analysis
   analysis_hosts: 
      chr1 : "../../data/references/chrs/chr1.fa"
      hg38: "../../data/references/GRCh38.fa"
       
   analysis_viruses:
      OTC :  "../../data/references/OTC-vec_rAAV-genome-only.fa"
   merge: 
       - True
   dedup: 
       - False
   post:
       -
         - filter
         - mask-exclude:
           - "../../data/references/hg38_homologoustoOTCvec.bed"
   bwa_mem:
       - "-A 1 -B 2 -O 6,6 -E 1,1 -L 0,0 -T 10 -h 200" 

   polyidus_params:
     aligner:
      - "bowtie2"

   vifi_params:
     host_info:
       chr1: 
         mappability: "../../vifi-test/data_repo/GRCh38/hg38full_k35_noMM.mappability.bedgraph"
         mappability_exclude: "../../data/references/GRCh38/ENCFF356LFX.bed"
         genes: "../../data/references/GRCh38/hg38.gencode.v35.annotation.genes.gff3"
         exons: "../../data/references/GRCh38/hg38.gencode.v35.annotation.exons.gff3"
         oncogenes: "../../data/references/GRCh38/hg38.gencode.v35.annotation.genes.gff3"
         centromeres: "../../data/references/GRCh38/centromeres.bed"
         conserved_regions: "../../data/references/GRCh38/exclude.cnvnator_100bp.GRCh38.20170403.bed"
         segdup: "../../data/references/GRCh38/genomicSuperDups.bed"
       hg38: 
         mappability: "../../vifi-test/data_repo/GRCh38/hg38full_k35_noMM.mappability.bedgraph"
         mappability_exclude: "../../data/references/GRCh38/ENCFF356LFX.bed"
         genes: "../../data/references/GRCh38/hg38.gencode.v35.annotation.genes.gff3"
         exons: "../../data/references/GRCh38/hg38.gencode.v35.annotation.exons.gff3"
         oncogenes: "../../data/references/GRCh38/hg38.gencode.v35.annotation.genes.gff3"
         centromeres: "../../data/references/GRCh38/centromeres.bed"
         conserved_regions: "../../data/references/GRCh38/exclude.cnvnator_100bp.GRCh38.20170403.bed"
         segdup: "../../data/references/GRCh38/genomicSuperDups.bed"
     vifi_dir: "../../ViFi"      

   # scoring
   score_ints: True
   score_ints_window: 20
