global:
   out_directory: "../../out/experiment1_OTC_chr1/AAV-OTC"
   
   # integration simulation
   replicates: 3 
   hosts: 
      chr1 : "../../data/references/GRCh38/chrs/chr1.fa" 
   
   # seed
   initial_seed: 1234567
   seed_increment: 123 
   
   # genome variation
   snp_count: 100000
   indel_count: 1000
   cnv_count: 0
   inversion_count: 0
   translocation_count: 0
   
   # integration parameters
   int_num: 
       - 1000
   # read simulation
   read_len: 
       - 250
   frag_len: 
       - 450
   frag_std: 
       - 25
   seq_sys: 
       - "MSv3"

   # analysis
   analysis_hosts: 
      hg38: "../../data/references/GRCh38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna"
       
   merge: 
       - False
   trim: 
       - False
   dedup: 
       - False

   bwa_mem:
       - "-a -Y -A 1 -B 2 -O 6,6 -E 1,1 -L 0,0 -T 10 -h 1,200"
   merge-method:
       - 'common'
   merge-n-min:
       - 1
   cigar-tol:
       - 3
   clip-cutoff:
       - 20
   mapq-threshold:
       - 20
   alt-edit-dist-thresh:
       - 3
   alt-edit-dist-thresh-pc:
       - null

   filter:
       -
         - "True"
       -
         - "NoAmbiguousBases < 20 or Type == discordant"
         - "PossibleVectorRearrangement == False"
       -
         - "PossibleVectorRearrangement == False" 
       -
         - "PossibleVectorRearrangement == False" 
         - "PossibleHostTranslocation == False" 
       -
         - "NoAmbiguousBases < 20 or Type == discordant"
         - "PossibleVectorRearrangement == False"
         - "PossibleHostTranslocation == False" 
         - "HostEditDist <= 7 or ViralEditDist <= 7"
         
   bed-exclude:
       -
         - "../../data/references/hg38_homologoustoOTCvec.bed" 
   bed-include:
       -
         - 
       
    # scoring
   score_reads: False
   score_ints: True
   score_merged_ints: True
   score_ints_window: 
    - 0
    - 5
    - 60

   score_ints_type: 
    - "coords_mean"
    - "coords_min"
    - "shortest"
    - "midpoint"
   
   # other tools 
   polyidus_params:
     aligner:
      - "bowtie2"
     trim:
       - False

   vifi_params:
     host_info:
       hg38: 
         mappability: "../../../Release/GRCh38/hg38full_k35_noMM.mappability.bedgraph"
         mappability_exclude: "../../../Release/GRCh38/exclude.cnvnator_100bp.GRCh38.20170403.bed"
         genes:  "../../../Release/GRCh38/Genes_hg38.gff"
         exons:  "../../../Release/GRCh38/Genes_hg38.gff"
         oncogenes:  "../../../Release/GRCh38/cancer/oncogenes/Census_oncomerge_hg38.gff"
         centromeres:  "../../../Release/GRCh38/GRCh38_centromere.bed"
         conserved_regions:  "../../../Release/GRCh38/conserved_gain5_hg38.bed"
         segdup:  "../../../Release/GRCh38/annotations/hg38GenomicSuperDup.tab"
     trim:
       - False
         
   # run verse
   # https://bioinfo.uth.edu/VirusFinder/VirusFinder-manual.pdf?csrt=2093584511125027598
#   verse_params:
#     detection_mode:
#      - sensitive
#     flank_region_size:
#      - 4000
#     sensitivity_level:
#      - 1
#     min_contig_length:
#      - 300
#     blastn_evalue_thrd:
#      - 0.05
#     similarity_thrd:
#      - 0.8
#     chop_read_length:
#      - 25
#     minIdentity:
#      - 80 

   seeksv_params:
     trim:
      - False
     dedup:
      - False
     min_reads:
      - 1
     merge_dist:
      - 100
        

AAV:
   viruses:
      AAV2 :  "../../data/references/NC_001401.2.fa"
   epi_num:
       - 100
   p_whole:
       - 0.3
   p_rearrange:
       - 0
   p_delete:
       - 0
   lambda_split:
       - 1
   p_overlap:
       - 0.3
   p_gap:
       - 0.3
   lambda_junction:
       - 1
   p_host_deletion:
       - 0.5
   lambda_host_deletion:
       - 500
   min_sep:
       - 100
   min_len:
       - 20
   # read simulation
   fcov: 
       - 5
   analysis_viruses:
      AAV2 :  "../../data/references/NC_001401.2.fa"
      
   vseq_toolkit_params:
     qua: 
      - 20
     lenPer: 
      - 50
     mode: 
      - default
     vecVecFusion: 
      - 'false'
     stringencyVec: 
      - 'medium'
     UMthresholdVec: 
      - 0.95
     minMapSpanVec: 
      - 20
     distVecVec: 
      - 10
     opVecVec: 
      - 5
     idenVecVec: 
      - 95
     stringencyVecGen: 
      - 'medium'
     UMthresholdVecGen: 
      - 0.95
     minMapSpanVecGen: 
      - 25
     distVecGen: 
      - 10
     opVecGen: 
      - 5
     idenVecGen: 
      - 95
     clusterRange: 
      - 3
     host_table:
       hg38: "$VSeqToolkit/testDir/testReferenceIndex/refSeqUCSCTablehg38.txt"  
   
OTC:
   viruses:
      OTC :  "../../data/references/OTC-vec_rAAV-genome-only.fa"
   epi_num:
       - 1000
   p_whole:
       - 0.3
   p_rearrange:
       - 0.1
   p_delete:
       - 0.1
   lambda_split:
       - 1
   p_overlap:
       - 0.3
   p_gap:
       - 0.3
   lambda_junction:
       - 1
   p_host_deletion:
       - 0.5
   lambda_host_deletion:
       - 500
   min_sep:
       - 100
   min_len:
       - 20
   # read simulation
   fcov: 
       - 1.5
   analysis_viruses:
      OTC :  "../../data/references/OTC-vec_rAAV-genome-only.fa"
      
   vseq_toolkit_params:
     qua: 
      - 20
     lenPer: 
      - 50
     mode: 
      - default
     vecVecFusion: 
      - 'true'
     stringencyVec: 
      - 'medium'
     UMthresholdVec: 
      - 0.95
     minMapSpanVec: 
      - 20
     distVecVec: 
      - 10
     opVecVec: 
      - 5
     idenVecVec: 
      - 95
     stringencyVecGen: 
      - 'medium'
     UMthresholdVecGen: 
      - 0.95
     minMapSpanVecGen: 
      - 25
     distVecGen: 
      - 10
     opVecGen: 
      - 5
     idenVecGen: 
      - 95
     clusterRange: 
      - 3
     host_table:
       hg38: "$VSeqToolkit/testDir/testReferenceIndex/refSeqUCSCTablehg38.txt"    
