global:
   out_directory: "../../out/experiment1_OTC_chr1/AAV-OTC"
   
   # integration simulation
   replicates: 3 
   hosts: 
      chr1 : "../../data/references/chrs/chr1.fa"
      hg38 : "../../data/references/GRCh38_main.fa" 
   
   initial_seed: 12345
   seed_increment: 123 
   int_num: 
       - 1000
   epi_num:
       - 0
   p_whole:
       - 1
   p_rearrange:
       - 0
   p_delete:
       - 0
   lambda_split:
       - 1
   p_overlap:
       - 0
   p_gap:
       - 0
   lambda_junction:
       - 5
   p_host_deletion:
       - 0
   lambda_host_deletion:
       - 500
   min_sep:
       - 500
   min_len:
       - 500
   # read simulation
   read_len: 
       - 250
   fcov: 
       - 5 
   frag_len: 
       - 500
   frag_std: 
       - 30
   seq_sys: 
       - "MSv3"

   # analysis
   analysis_hosts: 
      hg38: "../../data/references/GRCh38.fa"
       
   merge: 
       - False
   trim: 
       - True
   dedup: 
       - False
   post:
       -
         - filter
         - mask-exclude:
           - "../../data/references/hg38_homologoustoOTCvec.bed"
   bwa_mem:
       - "-A 1 -B 2 -O 6,6 -E 1,1 -L 0,0 -U 9 -T 20 -h 200"
   merge-dist:
       - 1000
   merge-n-min:
       - 1
   cigar-tol:
       - 2
   clip-cutoff:
       - 20
   min-mapq:
       - 20
       
    # scoring
   score_reads: False
   score_ints: True
   score_merged_ints: True
   score_ints_window: 
    - 5

   score_ints_type: 
    - "coords_mean"
   
   # other tools 
   polyidus_params:
     aligner:
      - "bowtie2"
     trim:
       - True

   vifi_params:
     host_info:
       hg38: 
         mappability: "../../data/references/data_repo/GRCh38/hg38full_k35_noMM.mappability.bedgraph"
         mappability_exclude: "../../data/references/data_repo/GRCh38/exclude.cnvnator_100bp.GRCh38.20170403.bed"
         genes:  "../../data/references/data_repo/GRCh38/Genes_hg38.gff"
         exons:  "../../data/references/data_repo/GRCh38/Genes_hg38.gff"
         oncogenes:  "../../data/references/data_repo/GRCh38/cancer/oncogenes/Census_oncomerge_hg38.gff"
         centromeres:  "../../data/references/data_repo/GRCh38/GRCh38_centromere.bed"
         conserved_regions:  "../../data/references/data_repo/GRCh38/conserved_gain5_hg38.bed"
         segdup:  "../../data/references/data_repo/GRCh38/annotations/hg38GenomicSuperDup.tab"
     trim:
       - True
         
   # run verse
   # https://bioinfo.uth.edu/VirusFinder/VirusFinder-manual.pdf?csrt=2093584511125027598
#   verse_params:
#     detection_mode:
#      - sensitive
#     flank_region_size:
#      - 4000
#     sensitivity_level:
#      - 1
#     min_contig_length:
#      - 300
#     blastn_evalue_thrd:
#      - 0.05
#     similarity_thrd:
#      - 0.8
#     chop_read_length:
#      - 25
#     minIdentity:
#      - 80 

   seeksv_params:
     trim:
      - True
     dedup:
      - False
     min_reads:
      - 1
     merge_dist:
      - 100
      
   vseq_toolkit_params:
     qua: 
      - 20
     lenPer: 
      - 50
     mode: 
      - default
     vecVecFusion: 
      - 'true'
     stringencyVec: 
      - 'medium'
     UMthresholdVec: 
      - 0.95
     minMapSpanVec: 
      - 20
     distVecVec: 
      - 10
     opVecVec: 
      - 5
     idenVecVec: 
      - 95
     stringencyVecGen: 
      - 'medium'
     UMthresholdVecGen: 
      - 0.95
     minMapSpanVecGen: 
      - 25
     distVecGen: 
      - 10
     opVecGen: 
      - 5
     idenVecGen: 
      - 95
     clusterRange: 
      - 3
     host_table:
       hg38: "$VSeqToolkit/testDir/testReferenceIndex/refSeqUCSCTablehg38.txt"      

AAV-harder:
   viruses:
      AAV2 :  "../../data/references/NC_001401_2.fa"
   epi_num:
       - 100
   p_whole:
       - 0.3
   p_rearrange:
       - 0
   p_delete:
       - 0
   lambda_split:
       - 1
   p_overlap:
       - 0.3
   p_gap:
       - 0.3
   lambda_junction:
       - 1
   p_host_deletion:
       - 0.5
   lambda_host_deletion:
       - 500
   min_sep:
       - 100
   min_len:
       - 20
   # read simulation
   fcov: 
       - 5
   analysis_viruses:
      AAV2 :  "../../data/references/NC_001401_2.fa"
   
OTC-harder:
   viruses:
      OTC :  "../../data/references/OTC-vec_rAAV-genome-only.fa"
   epi_num:
       - 1000
   p_whole:
       - 0.3
   p_rearrange:
       - 0.1
   p_delete:
       - 0.1
   lambda_split:
       - 1
   p_overlap:
       - 0.3
   p_gap:
       - 0.3
   lambda_junction:
       - 1
   p_host_deletion:
       - 0.5
   lambda_host_deletion:
       - 500
   min_sep:
       - 100
   min_len:
       - 20
   # read simulation
   fcov: 
       - 1.5
   analysis_viruses:
      OTC :  "../../data/references/OTC-vec_rAAV-genome-only.fa"
