global:
   out_directory: "../../out/experiment1_OTC_chr1/analysis-conditions"
   
   # integration simulation
   replicates: 3 
   hosts: 
      chr1 : "../../data/references/chrs/chr1.fa"
       
   viruses:
      OTC :  "../../data/references/OTC-vec_rAAV-genome-only.fa"
   
   initial_seed: 12345
   seed_increment: 123 
   int_num: 
       - 1000
   epi_num:
       - 0
   p_whole:
       - 1
   p_rearrange:
       - 0
   p_delete:
       - 0
   lambda_split:
       - 1
   p_overlap:
       - 0
   p_gap:
       - 0
   lambda_junction:
       - 5
   p_host_deletion:
       - 0
   lambda_host_deletion:
       - 500
   min_sep:
       - 500
   min_len:
       - 500
   # read simulation
   read_len: 
       - 150
   fcov: 
       - 5 
   frag_len: 
       - 500 
   frag_std: 
       - 30
   seq_sys: 
       - "MSv3"

   # analysis
   analysis_hosts: 
      hg38: "../../data/references/GRCh38.fa"
       
   analysis_viruses:
      OTC :  "../../data/references/OTC-vec_rAAV-genome-only.fa"
   merge: 
       - True
       - False
   trim:
       - True
       - False
   dedup: 
       - False
   post:
       -
         - filter
         - mask-exclude:
           - "../../data/references/hg38_homologoustoOTCvec.bed"
   bwa_mem:
       - "-A 1 -B 2 -O 6,6 -E 1,1 -L 0,0 -T 10 -h 200"
   merge-dist:
       - 10
       - 100
   merge-n-min:
       - 1
       - 3
   cigar-tol:
       - 1
       - 3
   clip-cutoff:
       - 20
   min-mapq:
       - 0
       - 10
       - 20     

   # scoring
   score_reads: False
   score_ints: True
   score_merged_ints: True
   score_ints_window: 20
   
   # other tools 
   polyidus_params:
     aligner:
      - "bowtie2"

   vifi_params:
     host_info:
       hg38: 
         mappability: "../../vifi-test/data_repo/GRCh38/hg38full_k35_noMM.mappability.bedgraph"
         mappability_exclude: "../../data/references/GRCh38/ENCFF356LFX.bed"
         genes: "../../data/references/GRCh38/hg38.gencode.v35.annotation.genes.gff3"
         exons: "../../data/references/GRCh38/hg38.gencode.v35.annotation.exons.gff3"
         oncogenes: "../../data/references/GRCh38/hg38.gencode.v35.annotation.genes.gff3"
         centromeres: "../../data/references/GRCh38/centromeres.bed"
         conserved_regions: "../../data/references/GRCh38/exclude.cnvnator_100bp.GRCh38.20170403.bed"
         segdup: "../../data/references/GRCh38/genomicSuperDups.bed"
     vifi_dir: "../../ViFi" 

OTC-vect-easier:
   replicates: 3 
   
OTC-vect-harder:
   epi_num:
       - 1000
   p_whole:
       - 0.3
   p_rearrange:
       - 0.1
   p_delete:
       - 0.1
   lambda_split:
       - 1
   p_overlap:
       - 0.3
   p_gap:
       - 0.3
   lambda_junction:
       - 1
   p_host_deletion:
       - 0.5
   lambda_host_deletion:
       - 500
   min_sep:
       - 100
   min_len:
       - 20
   # read simulation
   fcov: 
       - 1.5
   frag_len: 
       - 250


