OTC-vect-easier:
   out_directory: "../../out/experiment1_OTC_chr1/analysis_conditions"
   
   # integration simulation
   replicates: 3 
   hosts: 
      chr1 : "../../data/references/chrs/chr1.fa"
       
   viruses:
      OTC :  "../../data/references/OTC-vec_rAAV-genome-only.fa"
   
   initial_seed: 12345
   seed_increment: 123 
   int_num: 
       - 1000
   epi_num:
       - 0
   p_whole:
       - 1
   p_rearrange:
       - 0
   p_delete:
       - 0
   lambda_split:
       - 1
   p_overlap:
       - 0
   p_gap:
       - 0
   lambda_junction:
       - 1
   p_host_deletion:
       - 0
   lambda_host_deletion:
       - 500
   min_sep:
       - 500
   min_len:
       - 500
   # read simulation
   read_len: 
       - 150
   fcov: 
       - 5 
   frag_len: 
       - 500
   frag_std: 
       - 30
   seq_sys: 
       - "MSv3"

   # analysis
   analysis_hosts: 
      hg38: "../../data/references/GRCh38.fa"
       
   analysis_viruses:
      OTC :  "../../data/references/OTC-vec_rAAV-genome-only.fa"
   merge: 
       - True
       - False
   dedup: 
       - False
   post:
       -
         - filter
         - mask-exclude:
           - "../../data/references/hg38_homologoustoOTCvec.bed"
   bwa_mem:
       - "-A 1 -B 2 -O 6,6 -E 1,1 -L 0,0 -T 10 -h 200"
   merge-dist:
       - 100
   merge-n-min:
       - 1
       - 3
   cigar-tol:
       - 1
       - 3
       - 5
   clip-cutoff:
       - 20
       - 25
   min-mapq:
       - 0
       - 5
       - 10
       - 15
       - 20     

   # scoring
   score_ints: True
   score_ints_window: 20

OTC-vect-harder:
   out_directory: "../../out/experiment1_OTC_chr1/analysis_conditions"
   
   # integration simulation
   replicates: 3 
   hosts: 
      chr1 : "../../data/references/chrs/chr1.fa"
       
   viruses:
      OTC :  "../../data/references/OTC-vec_rAAV-genome-only.fa"
   
   initial_seed: 12345
   seed_increment: 123 
   int_num: 
       - 1000
   epi_num:
       - 1000
   p_whole:
       - 0.3
   p_rearrange:
       - 0.1
   p_delete:
       - 0.1
   lambda_split:
       - 1
   p_overlap:
       - 0.3
   p_gap:
       - 0.3
   lambda_junction:
       - 1
   p_host_deletion:
       - 0.5
   lambda_host_deletion:
       - 500
   min_sep:
       - 100
   min_len:
       - 20
   # read simulation
   read_len: 
       - 150
   fcov: 
       - 1.5 
   frag_len: 
       - 250
   frag_std: 
       - 30
   seq_sys: 
       - "MSv3"

   # analysis
   analysis_hosts: 
      hg38: "../../data/references/GRCh38.fa"
       
   analysis_viruses:
      OTC :  "../../data/references/OTC-vec_rAAV-genome-only.fa"
   merge: 
       - True
       - False
   dedup: 
       - False
   post:
       -
         - filter
         - mask-exclude:
           - "../../data/references/hg38_homologoustoOTCvec.bed"
   bwa_mem:
       - "-A 1 -B 2 -O 6,6 -E 1,1 -L 0,0 -T 10 -h 200"
   merge-dist:
       - 100
   merge-n-min:
       - 1
       - 3
   cigar-tol:
       - 1
       - 3
       - 5
   clip-cutoff:
       - 20
       - 25
   min-mapq:
       - 0
       - 5
       - 10
       - 15
       - 20

   # scoring
   score_ints: True
   score_ints_window: 20


