# things that are the same for all datasets
global:
   out_directory: "../../out/experiment1_OTC_chr1/condition-breakdown"
   
   # integration simulation
   replicates: 3 
   hosts: 
      chr1 : "../../data/references/chrs/chr1.fa"
       
   viruses:
      OTC :  "../../data/references/OTC-vec_rAAV-genome-only.fa"
   
   initial_seed: 12345
   seed_increment: 123 
   int_num: 
       - 1000
   epi_num:
       - 0
   p_whole:
       - 1
   p_rearrange:
       - 0
   p_delete:
       - 0
   lambda_split:
       - 1
   p_overlap:
       - 0
   p_gap:
       - 0
   lambda_junction:
       - 5
   p_host_deletion:
       - 0
   lambda_host_deletion:
       - 500
   min_sep:
       - 500
   min_len:
       - 500
   # read simulation
   read_len: 
       - 150
   fcov: 
       - 5 
   frag_len: 
       - 500 
   frag_std: 
       - 30
   seq_sys: 
       - "MSv3"

   # analysis
   analysis_hosts: 
      hg38: "../../data/references/GRCh38.fa"
       
   analysis_viruses:
      OTC :  "../../data/references/OTC-vec_rAAV-genome-only.fa"
   merge: 
       - False
   trim: 
       - True
   dedup: 
       - False
   post:
       -
         - filter
         - mask-exclude:
           - "../../data/references/hg38_homologoustoOTCvec.bed"
   bwa_mem:
       - "-A 1 -B 2 -O 6,6 -E 1,1 -L 0,0 -T 10 -h 200"
   merge-dist:
       - 100 
   merge-n-min:
       - 1
   cigar-tol:
       - 1
   clip-cutoff:
       - 20
   min-mapq:
       - 10
       
    # scoring
   score_reads: False
   score_ints: True
   score_merged_ints: True
   score_ints_window: 20 # window either side of simulated integrations to look for detected integrations  
   
   # other tools 
   polyidus_params:
     aligner:
      - "bowtie2"

   vifi_params:
     host_info:
       hg38: 
         mappability: "../../vifi-test/data_repo/GRCh38/hg38full_k35_noMM.mappability.bedgraph"
         mappability_exclude: "../../data/references/GRCh38/ENCFF356LFX.bed"
         genes: "../../data/references/GRCh38/hg38.gencode.v35.annotation.genes.gff3"
         exons: "../../data/references/GRCh38/hg38.gencode.v35.annotation.exons.gff3"
         oncogenes: "../../data/references/GRCh38/hg38.gencode.v35.annotation.genes.gff3"
         centromeres: "../../data/references/GRCh38/centromeres.bed"
         conserved_regions: "../../data/references/GRCh38/exclude.cnvnator_100bp.GRCh38.20170403.bed"
         segdup: "../../data/references/GRCh38/genomicSuperDups.bed"
     vifi_dir: "../../ViFi" 

# things that are different for each dataset
OTC-whole:
   p_whole:
       - 0
       - 0.25
       - 0.5
       - 0.75
       - 1

OTC-epi:
   epi_num:
       - 0 
       - 100
       - 1000
       - 100000
       - 10000000
 
OTC-rearrange:
   p_rearrange:
       - 0
       - 0.25
       - 0.5
       - 0.75
       - 1

OTC-deletion:
   p_delete:
       - 0
       - 0.25
       - 0.5
       - 0.75
       - 1

OTC-overlap:
   p_overlap:
       - 0
       - 0.25
       - 0.5
       - 0.75
       - 1

OTC-gap:
   p_gap:
       - 0
       - 0.25
       - 0.5
       - 0.75
       - 1
OTC-host_deletion:
   p_host_deletion:
       - 0
       - 0.25
       - 0.5
       - 0.75
       - 1

OTC-fcov:
   frag_len: 
       - 0.75
       - 1.5
       - 3
       - 6

OTC-frag_len:
   frag_len: 
       - 250
       - 300
       - 500 
       - 1000  
   
OTC-min_sep:
   min_sep:
       - 100
       - 300
       - 500
       - 800
       - 1000

OTC-min_len:
   min_len:
       - 20
       - 50
       - 100
       - 300
       - 500
       - 1000
