# things that are the same for all datasets
global:
   out_directory: "../../out/experiment1_OTC_chr1/OTC-condition-breakdown"
   
   # integration simulation
   replicates: 3 
       
   viruses:
      OTC :  "../../data/references/OTC-vec_rAAV-genome-only.fa"
   
   initial_seed: 1234567
   seed_increment: 123 
   
   # genome variation
   snp_count: 100000
   indel_count: 1000
   cnv_count: 10
   inversion_count: 2
   translocation_count: 1
   
   int_num: 
       - 1000
   epi_num:
       - 1000
   p_whole:
       - 0.3
   p_rearrange:
       - 0.1
   p_delete:
       - 0.1
   lambda_split:
       - 1
   p_overlap:
       - 0.3
   p_gap:
       - 0.3
   lambda_junction:
       - 1
   p_host_deletion:
       - 0.5
   lambda_host_deletion:
       - 500
   min_sep:
       - 100
   min_len:
       - 20
   # read simulation
   read_len: 
       - 250
   fcov: 
       - 1.5
   frag_len: 
       - 450
   frag_std: 
       - 25
   seq_sys: 
       - "MSv3"

   # analysis
   analysis_hosts: 
      hg38: "../../data/references/GRCh38.fa"
       
   analysis_viruses:
      OTC :  "../../data/references/OTC-vec_rAAV-genome-only.fa"
   merge: 
       - False
   trim: 
       - False
   dedup: 
       - False
   bwa_mem:
       - "-a -Y -A 1 -B 2 -O 6,6 -E 1,1 -L 0,0 -T 10 -h 1,200"
   merge-n-min:
       - 1
   merge-method:
       - "common"
   cigar-tol:
       - 3
   clip-cutoff:
       - 20
   mapq-threshold:
       - 20
   alt-edit-dist-thresh:
       - 3
   alt-edit-dist-thresh-pc:
       - null
   filter:
       -
         - "True"
       -
         - "NoAmbiguousBases < 20 or Type == discordant"
         - "PossibleVectorRearrangement == False"
       -
         - "PossibleVectorRearrangement == False" 
       -
         - "PossibleVectorRearrangement == False" 
         - "PossibleHostTranslocation == False" 
       -
         - "NoAmbiguousBases < 20 or Type == discordant"
         - "PossibleVectorRearrangement == False"
         - "PossibleHostTranslocation == False" 
         - "HostEditDist <= 7 or ViralEditDist <= 7"
   
   bed-exclude:
       -
         - "../../data/references/hg38_homologoustoOTCvec.bed" 
   bed-include:
       -
         - 
       
    # scoring
   score_reads: False
   score_ints: True
   score_merged_ints: True
   score_ints_window:
    - 0
    - 5
    - 60
   score_ints_type: 
    - "coords_mean"
    - "shortest"
   
   # other tools 
   polyidus_params:
     aligner:
      - "bowtie2"
     trim:
       - False

   vifi_params:
     host_info:
       hg38: 
         mappability: "../../data/references/data_repo/GRCh38/hg38full_k35_noMM.mappability.bedgraph"
         mappability_exclude: "../../data/references/data_repo/GRCh38/exclude.cnvnator_100bp.GRCh38.20170403.bed"
         genes:  "../../data/references/data_repo/GRCh38/Genes_hg38.gff"
         exons:  "../../data/references/data_repo/GRCh38/Genes_hg38.gff"
         oncogenes:  "../../data/references/data_repo/GRCh38/cancer/oncogenes/Census_oncomerge_hg38.gff"
         centromeres:  "../../data/references/data_repo/GRCh38/GRCh38_centromere.bed"
         conserved_regions:  "../../data/references/data_repo/GRCh38/conserved_gain5_hg38.bed"
         segdup:  "../../data/references/data_repo/GRCh38/annotations/hg38GenomicSuperDup.tab"
     trim:
       - False

   seeksv_params:
     trim:
      - False
     dedup:
      - False
     min_reads:
      - 1
     merge_dist:
      - 100

   vseq_toolkit_params:
     qua: 
      - 20
     lenPer: 
      - 50
     mode: 
      - 'default'
     vecVecFusion: 
      - 'true'
     stringencyVec: 
      - 'high'
     UMthresholdVec: 
      - 0.95
     minMapSpanVec: 
      - 20
     distVecVec: 
      - 10
     opVecVec: 
      - 5
     idenVecVec: 
      - 95
     stringencyVecGen: 
      - 'medium'
     UMthresholdVecGen: 
      - 0.95
     minMapSpanVecGen: 
      - 25
     distVecGen: 
      - 10
     opVecGen: 
      - 5
     idenVecGen: 
      - 95
     clusterRange: 
      - 3
     host_table:
       hg38: "$VSeqToolkit/testDir/testReferenceIndex/refSeqUCSCTablehg38.txt"      


# things that are different for each dataset

#OTC-frag_len:
#   frag_len: 
#       - 250
#       - 300
#       - 500 
#       - 1000  

chr-fcov:
   hosts: 
      chr1 : "../../data/references/chrs/chr1.fa"
      chr8 : "../../data/references/chrs/chr8.fa"
      chr14: "../../data/references/chrs/chr14.fa"
      chrX : "../../data/references/chrs/chrX.fa"
   fcov: 
       - 0.75
       - 1.5
       - 3
       - 6
       - 10
       - 30
       - 100   
       
#episomes:
#   p_rearrange:
#       - 0.1
#       - 0.7
#   p_delete:
#       - 0.7  
#       - 0.1
#   lambda_split:
#       - 2
#   epi_num:
#       - 0
#       - 1000      
#       - 1000000
